version: 0.3.{build}
image: Visual Studio 2017
services:
  - mssql2014           # start SQL Server 2014 Express
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "2.2.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
test: off
build:
  publish_nuget: true
  parallel: true 
  verbosity: detailed
build_script:
- cmd: PowerShell -Version 2.0 .\build.ps1 -Target Packages
artifacts:
  - path: 'nuget\*.nupkg'
  - path: 'build\*.*'
  - path: 'testResults\*.*'
notifications:
- provider: Email
  to:
  - aris.nikolaou@outlook.com
  subject: FutureState Build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false