// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FutureState.Data.Sql")]
[assembly: AssemblyProductAttribute("FutureState")]
[assembly: AssemblyDescriptionAttribute("FutureState")]
[assembly: AssemblyVersionAttribute("0.1")]
[assembly: AssemblyFileVersionAttribute("0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1";
    }
}
