// <auto-generated/>

using System.Reflection;

[assembly: AssemblyTitle("FutureState.Db.Setup")]
[assembly: AssemblyProduct("FutureState")]
[assembly: AssemblyVersion("0.3.0")]
[assembly: AssemblyFileVersion("0.3.0")]
[assembly:
    AssemblyInformationalVersion("0.1.0-flow-enrichment.1+185.Branch.feature/flow-enrichment.Sha.013db6b3a87908e3e3e3c029ba5150537169f1eb")]