// <auto-generated/>

using System.Reflection;

[assembly: AssemblyTitle("FutureState.Db.Setup")]
[assembly: AssemblyProduct("FutureState")]
[assembly: AssemblyDescription("FutureState")]
[assembly: AssemblyVersion("1.0")]
[assembly: AssemblyFileVersion("1.0")]
[assembly: AssemblyConfiguration("Release")]

namespace System
{
    internal static class AssemblyVersionInformation
    {
        internal const string AssemblyTitle = "FutureState.Db.Setup";
        internal const string AssemblyProduct = "FutureState";
        internal const string AssemblyDescription = "FutureState";
        internal const string AssemblyVersion = "1.0";
        internal const string AssemblyFileVersion = "1.0";
        internal const string AssemblyConfiguration = "Release";
    }
}