// <auto-generated/>

using System.Reflection;

[assembly: AssemblyTitle("FutureState.Db.Setup")]
[assembly: AssemblyProduct("FutureState")]
[assembly: AssemblyVersion("0.3.0")]
[assembly: AssemblyFileVersion("0.3.0")]
[assembly:
    AssemblyInformationalVersion("0.1.0-flow-enrichment.1+174.Branch.feature/flow-enrichment.Sha.4fd81a2b52f9af3a8a804a0ab842bb98fad1512d")]