namespace Dapper.FastCrud.Mappings
{
    /// <summary>
    ///     Discovers the orm mapping for a particular entity type.
    /// </summary>
    internal class AutoGeneratedEntityMapping<TEntity> : EntityMapping<TEntity>
    {
        /// <summary>
        ///     Default constructor.
        /// </summary>
        public AutoGeneratedEntityMapping()
        {
            var currentConventions = OrmConfiguration.Conventions;

            var tableName = currentConventions.GetTableName(EntityType);
            SetTableName(tableName);

            var schemaName = currentConventions.GetSchemaName(EntityType);
            {
                if (!string.IsNullOrEmpty(schemaName))
                    SetSchemaName(schemaName);
            }

            var entityProperties = currentConventions.GetEntityProperties(EntityType);
            var entityMap = SqlMapper.GetTypeMap(typeof(TEntity));

            foreach (var propDescriptor in entityProperties)
            {
                var entityMember = entityMap.GetMember(propDescriptor.Name);
                var propMapping = SetPropertyInternal(propDescriptor);
                if (entityMember != null)
                    propMapping.DatabaseColumnName = entityMember.ColumnName;

                currentConventions.ConfigureEntityPropertyMapping(propMapping);
            }
        }
    }
}