// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FutureState.Domain")]
[assembly: AssemblyProductAttribute("FutureState")]
[assembly: AssemblyDescriptionAttribute("FutureState")]
[assembly: AssemblyVersion("0.3.0")]
[assembly: AssemblyFileVersion("0.3.0")]
[assembly: AssemblyConfigurationAttribute("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "FutureState.Domain";
        internal const System.String AssemblyProduct = "FutureState";
        internal const System.String AssemblyDescription = "FutureState";
        internal const System.String AssemblyVersion = "1.0";
        internal const System.String AssemblyFileVersion = "1.0";
        internal const System.String AssemblyConfiguration = "Release";
    }
}

[assembly: AssemblyInformationalVersion("0.1.0-unstable.157+Branch.develop.Sha.ac017426cc158a694bcb5676065b0716c934b507")]
