// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FutureState.Domain")]
[assembly: AssemblyProductAttribute("FutureState")]
[assembly: AssemblyDescriptionAttribute("FutureState")]
[assembly: AssemblyVersion("0.4.0")]
[assembly: AssemblyFileVersion("0.4.0")]
[assembly: AssemblyConfigurationAttribute("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "FutureState.Domain";
        internal const System.String AssemblyProduct = "FutureState";
        internal const System.String AssemblyDescription = "FutureState";
        internal const System.String AssemblyVersion = "1.0";
        internal const System.String AssemblyFileVersion = "1.0";
        internal const System.String AssemblyConfiguration = "Release";
    }
}

[assembly: AssemblyInformationalVersion("0.1.0-unstable.123+Branch.develop.Sha.cfbd27a6dac43e9d7fbc93077ea962059b31e4e8")]
