// <auto-generated/>
using System.Reflection;

[assembly: AssemblyDescriptionAttribute("FutureState Enterprise Library")]

#if DEBUG
[assembly: AssemblyConfigurationAttribute("Debug")]
#elif RELEASE
[assembly: AssemblyConfigurationAttribute("Release")]
#endif
