// <auto-generated/>

using System.Reflection;

[assembly: AssemblyDescription("FutureState Enterprise Library")]

#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#elif RELEASE
[assembly: AssemblyConfiguration("Release")]
#endif