// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FutureState.App")]
[assembly: AssemblyProductAttribute("FutureState")]
[assembly: AssemblyDescriptionAttribute("FutureState")]
[assembly: AssemblyVersion("0.4.0")]
[assembly: AssemblyFileVersion("0.4.0")]
[assembly: AssemblyConfigurationAttribute("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "FutureState.App";
        internal const System.String AssemblyProduct = "FutureState";
        internal const System.String AssemblyDescription = "FutureState";
        internal const System.String AssemblyVersion = "1.0";
        internal const System.String AssemblyFileVersion = "1.0";
        internal const System.String AssemblyConfiguration = "Release";
    }
}

[assembly: AssemblyInformationalVersion("0.1.0-unstable.120+Branch.develop.Sha.f684998826fe7ecb1eb1631e531c51a82d8aef2a")]
